In [1]:
!pip install tensorflow

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("D:\\Datasets-main\\Churn_Modelling.csv")
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

# Data Transformation

In [5]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [6]:
df = pd.get_dummies(data=df, columns=['Geography','Gender'])
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1                 1   
1                  1        112542.58       0                 0   
2                  0        113931.57       1                 1   
3                  0         93826.63       0                 1   
4                  1         79084.10       0                 0   
...              ...              ...     ...               ...   
9995               0         96270.64       0                 1   
9996               1        101699.77       0                 1   
9997               1         42085.58       1                 1   
9998               0         92888.52       1                 0   
9999               0         38190.78       0                 1   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                     0                0              1            0  
1                     0                1              1            0  
2                     0                0              1            0  
3                     0                0              1            0  
4                     0                1              1            0  
...                 ...              ...            ...          ...  
9995                  0                0              0            1  
9996                  0                0              0            1  
9997                  0                0              1            0  
9998                  1                0              0            1  
9999                  0                0              1            0  

[10000 rows x 14 columns]

# Model Building

In [7]:
sc = StandardScaler()
x = df.drop(columns=['Exited'])
y = df['Exited']

In [8]:
x = sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [9]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20, random_state=1)

In [10]:
#Initialize model
ann = Sequential()

#Add hidden layer
ann.add(Dense(units=10,activation='relu'))

#Add output layer
ann.add(Dense(units=1, activation='sigmoid'))

#Establish the connection between the layers
ann.compile(optimizer = 'adadelta',loss='binary_crossentropy',metrics='accuracy')

#Fit the data
ann.fit(xtrain,ytrain, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 4ms/step - loss: 0.7692 - accuracy: 0.4271
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.7681 - accuracy: 0.4285
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.7669 - accuracy: 0.4304
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.7656 - accuracy: 0.4322
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.7644 - accuracy: 0.4341
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.7630 - accuracy: 0.4360
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.7617 - accuracy: 0.4365
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.7604 - accuracy: 0.4383
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.7590 - accuracy: 0.4403
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.7577 - accura

In [11]:
ypred = ann.predict(xtest)
ypred

63/63 [==============================] - 0s 3ms/step


array([[0.519839  ],
       [0.22730082],
       [0.49550724],
       ...,
       [0.4376087 ],
       [0.5765109 ],
       [0.34144536]], dtype=float32)

In [12]:
ypred > 0.5

array([[ True],
       [False],
       [False],
       ...,
       [False],
       [ True],
       [False]])

In [13]:
ypred = ypred > 0.5
ypred

array([[ True],
       [False],
       [False],
       ...,
       [False],
       [ True],
       [False]])

In [14]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [15]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.83      0.66      0.74      1585
           1       0.28      0.49      0.36       415

    accuracy                           0.63      2000
   macro avg       0.56      0.58      0.55      2000
weighted avg       0.72      0.63      0.66      2000



In [16]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

# Hyperparameter Tuning

In [17]:
!pip install -U keras-tuner

# Tuning the ANN Model

In [18]:
import keras_tuner as kt

Using TensorFlow backend


In [19]:
def optimizer_selection(hp):
    #initialize the model
    model = Sequential()
    #Add hidden layer
    model.add(Dense(units=10, activation='relu'))
    #Add output layer
    model.add(Dense(units=1, activation='sigmoid'))
    #Optimizer selection
    optim = hp.Choice('optimizer', values = ['sgd','adam','rmsprop'])
    model.compile(optimizer=optim, loss = 'binary_crossentropy', metrics = 'accuracy')
    return model

In [20]:
tuner = kt.RandomSearch(
    optimizer_selection,
    objective='val_accuracy',
    max_trials=3
)

Reloading Tuner from .\untitled_project\tuner0.json


In [21]:
tuner.search(xtrain,ytrain, epochs = 3, validation_data = (xtest,ytest))

In [22]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [23]:
model = tuner.get_best_models(num_models=1)[0]
model.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
250/250 [==============================] - 2s 5ms/step - loss: 0.4374 - accuracy: 0.8169 - val_loss: 0.4284 - val_accuracy: 0.8170
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4229 - accuracy: 0.8195 - val_loss: 0.4156 - val_accuracy: 0.8240
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4131 - accuracy: 0.8239 - val_loss: 0.4065 - val_accuracy: 0.8310
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4038 - accuracy: 0.8288 - val_loss: 0.3981 - val_accuracy: 0.8345
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3948 - accuracy: 0.8331 - val_loss: 0.3898 - val_accuracy: 0.8400
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3865 - accuracy: 0.8374 - val_loss: 0.3824 - val_accuracy: 0.8400
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3793 - accuracy: 0.8430 - val_loss: 0.3759 - val_accuracy: 0.8440

Epoch 58/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3358 - accuracy: 0.8614 - val_loss: 0.3369 - val_accuracy: 0.8620
Epoch 59/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3353 - accuracy: 0.8620 - val_loss: 0.3355 - val_accuracy: 0.8625
Epoch 60/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3352 - accuracy: 0.8615 - val_loss: 0.3359 - val_accuracy: 0.8650
Epoch 61/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3351 - accuracy: 0.8614 - val_loss: 0.3361 - val_accuracy: 0.8645
Epoch 62/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3354 - accuracy: 0.8619 - val_loss: 0.3379 - val_accuracy: 0.8600
Epoch 63/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3351 - accuracy: 0.8624 - val_loss: 0.3371 - val_accuracy: 0.8620
Epoch 64/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3350 - accuracy: 0.8615 - val_loss: 0.3372 - val_accuracy:

# Regression

In [24]:
df = pd.read_csv("D:\\Datasets-main\\Regression.csv")
df

price     feature1     feature2
0    461.527929   999.787558   999.766096
1    548.130012   998.861615  1001.042403
2    410.297162  1000.070267   998.844015
3    540.382220   999.952251  1000.440940
4    546.024553  1000.446011  1000.338531
..          ...          ...          ...
995  476.526078  1000.018988   999.672732
996  457.313186   998.855379  1000.020026
997  456.720993  1001.451646   998.847605
998  403.315576  1000.771023   998.562851
999  599.367094   999.232244  1001.451407

[1000 rows x 3 columns]

In [25]:
x = df.iloc[:,1:]
y = df['price']

In [26]:
x = sc.fit_transform(x)
x

array([[-0.23277509, -0.22551031],
       [-1.18389307,  1.12100979],
       [ 0.05762098, -1.19831827],
       ...,
       [ 1.47655818, -1.19452982],
       [ 0.77742978, -1.49494959],
       [-0.80318737,  1.55251428]])

In [27]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=1)

In [28]:
ann = Sequential()

ann.add(Dense(units=30, activation='relu'))
ann.add(Dense(units=20, activation='relu'))

ann.add(Dense(units=1))

ann.compile(optimizer='adam',loss = 'mse')

ann.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
25/25 [==============================] - 1s 17ms/step - loss: 255705.5156 - val_loss: 262407.5312
Epoch 2/100
25/25 [==============================] - 0s 7ms/step - loss: 255096.9844 - val_loss: 261738.7656
Epoch 3/100
25/25 [==============================] - 0s 8ms/step - loss: 254285.2031 - val_loss: 260784.7969
Epoch 4/100
25/25 [==============================] - 0s 7ms/step - loss: 253118.0938 - val_loss: 259396.6562
Epoch 5/100
25/25 [==============================] - 0s 8ms/step - loss: 251439.5938 - val_loss: 257390.2344
Epoch 6/100
25/25 [==============================] - 0s 7ms/step - loss: 249003.0781 - val_loss: 254524.3594
Epoch 7/100
25/25 [==============================] - 0s 6ms/step - loss: 245595.0625 - val_loss: 250602.6875
Epoch 8/100
25/25 [==============================] - 0s 7ms/step - loss: 241041.2969 - val_loss: 245467.9375
Epoch 9/100
25/25 [==============================] - 0s 7ms/step - loss: 235180.6875 - val_loss: 238932.5469
Epoch 10/100
25/25

In [29]:
yp = ann.predict(xtest)
yp

7/7 [==============================] - 0s 2ms/step


array([[478.61166],
       [524.21155],
       [499.36566],
       [539.3491 ],
       [652.0006 ],
       [341.14517],
       [365.48685],
       [363.2898 ],
       [712.8395 ],
       [509.37408],
       [483.8459 ],
       [507.33292],
       [499.15567],
       [374.00037],
       [545.89575],
       [493.91235],
       [574.77856],
       [547.5021 ],
       [486.31134],
       [499.10602],
       [476.07227],
       [604.40906],
       [443.39212],
       [576.7361 ],
       [427.10812],
       [521.5325 ],
       [377.6876 ],
       [502.07407],
       [540.626  ],
       [339.14948],
       [446.53635],
       [640.0771 ],
       [559.90155],
       [539.36194],
       [603.7174 ],
       [554.4552 ],
       [417.69473],
       [570.16125],
       [567.3756 ],
       [526.07086],
       [420.07584],
       [724.17896],
       [523.951  ],
       [529.5708 ],
       [521.8362 ],
       [465.66397],
       [531.40204],
       [526.47473],
       [583.67944],
       [468.24188],


In [37]:
ann.history.history

{}

In [34]:
#'history.history' function stores the training loss and test loss in dictionary format.
loss = pd.DataFrame(ann.history.history)
loss

Empty DataFrame
Columns: []
Index: []

In [35]:
loss.plot()

TypeError: no numeric data to plot

In [31]:
from sklearn.metrics import r2_score

In [32]:
r2_score(ytest,yp)

0.9661797394443804